#ifndef R2_FFI_H
#define R2_FFI_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C function pointer for upload progress updates.
 * Parameters: bytes_uploaded, total_bytes, speed_bytes_per_sec, eta_seconds
 * Swift passes this when starting uploads to get real-time progress.
 * In C: `typedef void (*R2ProgressCallback)(uint64_t, uint64_t, double, double);`
 * Pass NULL in Swift/C to disable progress reporting.
 */
typedef void (*R2ProgressCallback)(uint64_t bytes_uploaded,
                                   uint64_t total_bytes,
                                   double speed_bps,
                                   double eta_secs);

/**
 * Returns the last error message from an FFI call.
 * Caller must free the returned string with `r2_free_string`.
 * Returns null if no error occurred since the last call.
 */
char *r2_get_last_error(void);

/**
 * Frees a string previously allocated by the Rust FFI layer.
 *
 * # Safety
 * `ptr` must be a pointer returned by an r2_* function, or null.
 */
void r2_free_string(char *ptr);

/**
 * Initialize the audit logging system with rolling file output (FR-067).
 * Call once at app startup. Subsequent calls are no-ops.
 * `max_log_files` controls how many rotated log files to retain.
 * `max_log_file_size_mb` controls the max size (MB) before startup cleanup.
 * Returns 0 on success, -1 on error.
 */
int32_t r2_init_logging(uint16_t max_log_files, uint16_t max_log_file_size_mb);

/**
 * Inform the Rust engine of a network availability change.
 * Called by the Swift NWPathMonitor wrapper when connectivity changes.
 * `available`: true = network is up, false = network is down.
 * Returns 0 on success.
 */
int32_t r2_set_network_available(bool available);

/**
 * Returns the config directory path (~/.r2drop or R2DROP_HOME).
 * Caller must free the returned string with `r2_free_string`.
 */
char *r2_config_dir(void);

/**
 * Validate an API token against the Cloudflare API.
 * On success, returns a C string containing the token ID (UUID) from the
 * Cloudflare verify response. Caller must free with `r2_free_string`.
 * On failure, returns null (check r2_get_last_error).
 *
 * # Safety
 * `token` must be a valid NUL-terminated C string.
 */
char *r2_validate_token(const char *token);

/**
 * List Cloudflare accounts accessible with the given token.
 * Returns a JSON array: [{"id":"...","name":"..."},...]
 * Caller must free the returned string with `r2_free_string`.
 *
 * # Safety
 * `token` must be a valid NUL-terminated C string.
 */
char *r2_list_accounts(const char *token);

/**
 * List R2 buckets for the given account.
 * Returns a JSON array of bucket name strings: ["bucket-a","bucket-b",...]
 * Caller must free the returned string with `r2_free_string`.
 *
 * # Safety
 * `account_id` and `token` must be valid NUL-terminated C strings.
 */
char *r2_list_buckets(const char *account_id, const char *token);

/**
 * Create a new R2 bucket in the given account.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * All pointer params must be valid NUL-terminated C strings.
 */
int32_t r2_create_bucket(const char *account_id, const char *bucket_name, const char *token);

/**
 * Check if an object exists in R2 and return its metadata as JSON.
 * Returns JSON: {"exists":true,"content_length":1234,"last_modified":"1706..."} or
 * {"exists":false} if the object does not exist.
 * Returns null on error (check r2_get_last_error).
 * Caller must free the returned string with `r2_free_string`.
 *
 * # Safety
 * All pointer params must be valid NUL-terminated C strings.
 */
char *r2_head_object(const char *account_id,
                     const char *token,
                     const char *bucket,
                     const char *key);

/**
 * Queue a file for upload. Returns the job ID (>0) on success, -1 on error.
 * The file is not uploaded immediately — the runner processes the queue.
 *
 * # Safety
 * All pointer params must be valid NUL-terminated C strings.
 */
int64_t r2_queue_upload(const char *file_path,
                        const char *r2_key,
                        const char *bucket,
                        const char *account_name);

/**
 * Process pending upload jobs for a specific account.
 * Recovers any interrupted uploads, then processes all pending jobs.
 * Returns the number of jobs completed (>= 0) on success, -1 on error.
 *
 * # Safety
 * All pointer params must be valid NUL-terminated C strings.
 * `access_key_id` is the token UUID from validate_token.
 * `secret_access_key` is the SHA-256 hash of the API token.
 */
int32_t r2_process_queue(const char *account_id,
                         const char *access_key_id,
                         const char *secret_access_key,
                         const char *account_name);

/**
 * Pause an upload job. Returns 0 on success, -1 on error.
 */
int32_t r2_pause_upload(int64_t job_id);

/**
 * Resume a paused upload job (transitions to Pending for re-processing).
 * Returns 0 on success, -1 on error.
 */
int32_t r2_resume_upload(int64_t job_id);

/**
 * Cancel an upload job by deleting it from the queue.
 * Returns 0 on success (including if already deleted), -1 on error.
 */
int32_t r2_cancel_upload(int64_t job_id);

/**
 * Reset retry count and re-queue a failed job for manual retry.
 * Transitions status from Failed → Pending and resets retry_count to 0.
 * Returns 0 on success, -1 on error.
 */
int32_t r2_retry_job(int64_t job_id);

/**
 * Get the current queue status as a JSON array of job objects.
 * Each object: id, file_path, r2_key, bucket, account_name, status,
 * bytes_uploaded, total_bytes, error_message.
 * Caller must free the returned string with `r2_free_string`.
 */
char *r2_get_queue_status(void);

/**
 * Get upload history as a JSON array.
 * Each object: id, file_name, file_size, r2_key, bucket, account_name,
 * url, uploaded_at.
 * Caller must free the returned string with `r2_free_string`.
 */
char *r2_get_history(void);

#endif  /* R2_FFI_H */
